### PR TITLE
Solving #21 - Enhancment if else clause

### PR DESCRIPTION
**Pull request by Nopzen**
Solves #21 

I've updatede the else if clause in the `validator.js` to throw more "loud" errors and to generate a stack trace, this is done though the new constant `EventHandler` which is a class that extends the native Error class.

The reason for this was i discovered how "vague" we threw errors, instead of throwing and actual error the system would just return the validator false, and exit the compile, and throw a silent error in the console, i found this not very useful, and decided to enhance the tool with a proper else if clause and error handling.

*validation*
- [x] Updatede tests, and they succeds
- [x] Implmentede zipcelx in a small sandbox testede that it actually threw the errors
- [ ] Revise the pull request comments
@egeriis would you have a look at this PR

### CODE REVIEW

**Review by egeriis — CHANGES_REQUESTED** [review]
Please see this thread regarding extending `Error`. It's unfortunately not as straight forward as one might think: https://stackoverflow.com/questions/1382107/whats-a-good-way-to-extend-error-in-javascript

**Comment by Nopzen** [comment]
@egeriis ill have a look at it.

**Comment by Nopzen** [comment]
Should be working new with the information from the stackoverflow. Tests are implemented and parsing, and here is a screenshot of browser starting to throw:

skaermbillede 2018-06-13 kl 22 07 04

**Comment by Nopzen** [comment]
closing this, as fork has been killed.

**Pull request closed without merging**
