### PR TITLE
Add multiple sheets

### PR DESCRIPTION
**Pull request by ghost**
I needed the ability to create multiple worksheets/tabs so I created a new config like this. 

```
const config = {
    filename: 'Test',
    sheets: {
      sheet1: {
        data: [
          [{
            value: 'Income - Webshop',
            type: 'string'
          }, {
            value: 1000,
            type: 'number'
          }]
        ],
        sheetName: 'Test Sheet'
      },
      sheet2: {
        data: [
          [{
            value: 'Income - Webshop2',
            type: 'string'
          }, {
            value: 2000,
            type: 'number'
          }]
        ],
        sheetName: 'Test Sheet2'
      }
      
    }
  };
```

### CODE REVIEW

**Comment by davidryansoftware** [comment]
Ran CI locally, all tests pass and no linting errors. Although I had to add the 'testURL' property to the jest config to get Jest to run without errors.

**Comment by erisman20** [comment]
I would definitely love the option to have multiple sheets! Seems like it would be better to make the sheets property an array of sheet objects though.

**Comment by davidryansoftware** [comment]
I created a forked npm version of this, since needed it in my own project. https://www.npmjs.com/package/xlsxfromjson @linuws @erisman20

**Comment by egeriis** [comment]
Gonna close this, since the discussion has stalled 🙂

**Comment by elliotstoner** [comment]
Just throwing it out there that I am definitely looking to use multiple sheets. My two cents - I think it makes more sense to have `sheets` be an array of Sheet objects.

In the meantime I'll probably use the fork from @davidryansoftware (depending on how much free time I have I might convert the sheets object to an array).

**Pull request closed without merging**
